/*
 * APIMATICCalculatorLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package io.apimatic.examples;

import io.apimatic.examples.http.request.HttpRequest;

public class CustomAuthUtility {
    /**
    * Appends the necessary Custom Authentication credentials for making this authorized call
    * @param request The out going request to access the resource
    */
    public static void appendCustomAuthParams(HttpRequest request) {
        // TODO: Add your custom authentication here
        // The following properties are available to use
        //     Configuration.there
        //     Configuration.here
        //     Configuration.mnew
        // 
        // ie. Add a header through:
        //     request.getHeaders().put("Key", "Value");
    }
}